export const dimensionOrder = [
  "sweet",
  "funk",
  "bitter",
  "budget",
  "risk",
  "social",
  "dark",
];

export const dimensions = {
  sweet: {
    name: "甜糯偏好",
    low: "清淡/尝鲜",
    high: "高甜爆浆",
  },
  funk: {
    name: "臭味接受",
    low: "奶香克制",
    high: "越冲越上头",
  },
  bitter: {
    name: "苦甜接受",
    low: "拒绝苦味",
    high: "老饕苦甜",
  },
  budget: {
    name: "预算强度",
    low: "价格敏感",
    high: "品质优先",
  },
  risk: {
    name: "风险接受",
    low: "稳妥保障",
    high: "敢试敢冲",
  },
  social: {
    name: "分享裂变",
    low: "自己知道就好",
    high: "必须发出去",
  },
  dark: {
    name: "黑暗品接受",
    low: "只要体面果",
    high: "越裂越想试",
  },
};

export const questions = [
  {
    id: "fear",
    title: "你买榴莲最怕哪种翻车？",
    intentLabel: "核心顾虑",
    options: [
      {
        label: "夹生、少肉、售后扯皮",
        scores: { risk: 1, budget: 2, dark: 1 },
        tags: { concern: "怕夹生/怕售后", intent: 2 },
      },
      {
        label: "太贵，买错一颗等于心碎",
        scores: { budget: 1, risk: 1, dark: 2 },
        tags: { concern: "价格敏感", intent: 2 },
      },
      {
        label: "味道太冲，宿舍会把我审判",
        scores: { funk: 1, social: 2, risk: 1 },
        tags: { concern: "怕味道太冲", intent: 2 },
      },
      {
        label: "没那么怕，我主要想吃得刺激",
        scores: { funk: 3, risk: 3, bitter: 2, dark: 3 },
        tags: { concern: "想尝鲜", intent: 4 },
      },
    ],
  },
  {
    id: "smell",
    title: "你能接受的榴莲味道到哪一档？",
    intentLabel: "臭味阈值",
    options: [
      {
        label: "奶香微臭，别上来就暴击",
        scores: { sweet: 3, funk: 1, bitter: 1, risk: 1 },
        tags: { flavor: "新手奶香", intent: 3 },
      },
      {
        label: "正常榴莲味，甜糯最重要",
        scores: { sweet: 3, funk: 2, bitter: 1, risk: 2 },
        tags: { flavor: "甜糯稳定", intent: 3 },
      },
      {
        label: "苦甜浓郁也行，越吃越懂",
        scores: { sweet: 2, funk: 3, bitter: 3, budget: 3 },
        tags: { flavor: "苦甜老饕", intent: 4 },
      },
      {
        label: "越怪越想试，我要被榴莲教育",
        scores: { funk: 3, bitter: 3, risk: 3, dark: 3 },
        tags: { flavor: "重口探索", intent: 4 },
      },
    ],
  },
  {
    id: "taste",
    title: "你心里的理想口感更像哪种？",
    intentLabel: "口感偏好",
    options: [
      {
        label: "甜糯绵密，像水果界奶油蛋糕",
        scores: { sweet: 3, funk: 1, bitter: 1, social: 3 },
        tags: { flavor: "甜糯", intent: 4 },
      },
      {
        label: "厚重浓郁，带一点成熟的苦甜",
        scores: { sweet: 2, funk: 3, bitter: 3, budget: 3 },
        tags: { flavor: "浓郁苦甜", intent: 4 },
      },
      {
        label: "干净方便，最好拆开就能吃",
        scores: { sweet: 2, funk: 1, bitter: 1, risk: 1 },
        tags: { form: "冷冻果肉", intent: 3 },
      },
      {
        label: "便宜够香就行，外观不重要",
        scores: { budget: 1, risk: 3, dark: 3, funk: 2 },
        tags: { form: "性价比果", intent: 4 },
      },
    ],
  },
  {
    id: "budget",
    title: "这次预算比较接近哪一档？",
    intentLabel: "预算区间",
    options: [
      {
        label: "人均一杯奶茶钱，拼一下可以",
        scores: { budget: 1, social: 3, risk: 2, dark: 2 },
        tags: { budgetText: "低预算/拼团", intent: 3 },
      },
      {
        label: "中等价位，稳稳吃到就好",
        scores: { budget: 2, risk: 1, sweet: 3 },
        tags: { budgetText: "中预算/稳妥", intent: 4 },
      },
      {
        label: "贵一点可以，但要有品质理由",
        scores: { budget: 3, bitter: 2, funk: 2, risk: 1 },
        tags: { budgetText: "高预算/品质", intent: 4 },
      },
      {
        label: "看直播气氛，冲动起来我自己都怕",
        scores: { budget: 3, risk: 3, social: 3, dark: 2 },
        tags: { budgetText: "直播冲动型", intent: 5 },
      },
    ],
  },
  {
    id: "scene",
    title: "你最可能在哪个场景吃它？",
    intentLabel: "购买场景",
    options: [
      {
        label: "宿舍/办公室拼团，大家一起开果",
        scores: { social: 3, budget: 1, sweet: 3, risk: 1 },
        tags: { scene: "拼团", intent: 4 },
      },
      {
        label: "一个人奖励自己，今晚就要爽",
        scores: { social: 1, budget: 2, risk: 2, funk: 2 },
        tags: { scene: "独享", intent: 4 },
      },
      {
        label: "送人/聚会，不能太抽象",
        scores: { social: 3, budget: 3, risk: 1, dark: 1 },
        tags: { scene: "送礼/聚会", intent: 4 },
      },
      {
        label: "直播间/社群看到合适就下单",
        scores: { social: 3, budget: 2, risk: 3, dark: 2 },
        tags: { scene: "直播间", intent: 5 },
      },
    ],
  },
  {
    id: "dark",
    title: "如果榴莲长得丑、裂口，但便宜且说明清楚，你会？",
    intentLabel: "黑暗品接受",
    options: [
      {
        label: "完全不考虑，我要标准体面果",
        scores: { dark: 1, risk: 1, budget: 3 },
        tags: { darkIntent: "拒绝黑暗品", intent: 2 },
      },
      {
        label: "便宜很多可以，但必须讲清风险",
        scores: { dark: 2, risk: 2, budget: 1 },
        tags: { darkIntent: "谨慎尝试黑暗品", intent: 3 },
      },
      {
        label: "有故事就想试，适合今晚开吃就行",
        scores: { dark: 3, risk: 3, budget: 1, social: 3 },
        tags: { darkIntent: "高黑暗品意愿", intent: 5 },
        hiddenSignal: "crack",
      },
      {
        label: "越怪越好，我要发朋友圈审判它",
        scores: { dark: 3, risk: 3, social: 3, funk: 3 },
        tags: { darkIntent: "黑暗品传播型", intent: 5 },
        hiddenSignal: "crack",
      },
    ],
  },
  {
    id: "decision",
    title: "你最容易被哪种信息打动？",
    intentLabel: "决策触发",
    options: [
      {
        label: "真实开果图、出肉率、包熟说明",
        scores: { risk: 1, budget: 2, social: 1 },
        tags: { trigger: "品质保障", intent: 4 },
      },
      {
        label: "朋友说好吃，比广告有用",
        scores: { social: 3, risk: 2, sweet: 2 },
        tags: { trigger: "熟人推荐", intent: 4 },
      },
      {
        label: "主播讲得清楚，现场气氛到位",
        scores: { social: 3, risk: 3, budget: 2 },
        tags: { trigger: "直播话术", intent: 5 },
      },
      {
        label: "价格香，缺点也明说，我会自己判断",
        scores: { budget: 1, risk: 3, dark: 3 },
        tags: { trigger: "价格/透明风险", intent: 5 },
      },
    ],
  },
  {
    id: "share",
    title: "测完如果结果有点准，你会怎么处理？",
    intentLabel: "裂变意愿",
    options: [
      {
        label: "自己看看就好，不想发",
        scores: { social: 1, risk: 1 },
        tags: { share: "低分享", intent: 2 },
      },
      {
        label: "发给朋友看看，顺手吐槽两句",
        scores: { social: 2, sweet: 2 },
        tags: { share: "私聊分享", intent: 3 },
      },
      {
        label: "结果好笑就发朋友圈/群聊",
        scores: { social: 3, dark: 2 },
        tags: { share: "公开分享", intent: 4 },
      },
      {
        label: "直接拉人一起测，顺便拼一单",
        scores: { social: 3, budget: 1, risk: 2 },
        tags: { share: "裂变拼团", intent: 5 },
      },
    ],
  },
  {
    id: "afterSale",
    title: "下面哪句话最能提高你的下单信心？",
    intentLabel: "信任需求",
    options: [
      {
        label: "签收后包熟，有问题能售后",
        scores: { risk: 1, budget: 2, dark: 1 },
        tags: { trust: "包熟售后", intent: 4 },
      },
      {
        label: "产地、品种、熟度、重量都写清楚",
        scores: { risk: 1, bitter: 2, budget: 3 },
        tags: { trust: "信息透明", intent: 4 },
      },
      {
        label: "主播现场解释怎么吃、怎么存",
        scores: { social: 3, risk: 2, sweet: 2 },
        tags: { trust: "直播教育", intent: 5 },
      },
      {
        label: "缺点明说，便宜合理，我能接受",
        scores: { dark: 3, risk: 3, budget: 1 },
        tags: { trust: "风险透明", intent: 5 },
      },
    ],
  },
  {
    id: "buyNow",
    title: "如果现在给你一个匹配推荐，你的状态更像？",
    intentLabel: "即时购买意愿",
    options: [
      {
        label: "只是玩玩，暂时不买",
        scores: { social: 2, risk: 1, budget: 1 },
        tags: { buyStage: "娱乐用户", intent: 1 },
      },
      {
        label: "先收藏，有合适价格再说",
        scores: { budget: 1, risk: 1, social: 2 },
        tags: { buyStage: "收藏观望", intent: 3 },
      },
      {
        label: "推荐靠谱的话，可以今天下单",
        scores: { budget: 2, risk: 2, sweet: 3 },
        tags: { buyStage: "可转化", intent: 4 },
      },
      {
        label: "给我链接，我要开果局",
        scores: { budget: 3, risk: 3, social: 3, dark: 2 },
        tags: { buyStage: "强转化", intent: 5 },
      },
    ],
  },
];

export const typeLibrary = {
  "GOLD-I": {
    code: "GOLD-I",
    name: "金枕显眼包",
    pattern: "HLLMLHL",
    variety: "泰国金枕",
    form: "整果 / 拼团装",
    cardLine: "甜糯外向，看到倒计时就想喊朋友开果。",
    desc: "你适合从甜糯、低风险、接受度高的榴莲开始。金枕能降低第一次购买门槛，也适合宿舍或办公室一起分。",
    avoid: "优先选择有包熟说明、出肉率说明和售后承诺的商品。",
    merchantSignal: "高分享潜力的新手用户，适合推金枕拼团和直播间新手话术。",
    liveHook: "第一次吃榴莲别上来就挑战高难度，金枕才是新手村村长。",
    color: "#f7c948",
    accent: "#2f9e44",
  },
  "MUSANG-P": {
    code: "MUSANG-P",
    name: "猫山王贵族",
    pattern: "HHHHMML",
    variety: "猫山王",
    form: "高端果肉 / 礼盒",
    cardLine: "预算不怂，嘴巴很刁，普通甜已经哄不住你。",
    desc: "你更看重浓郁风味和品质确定性。猫山王适合做高客单推荐，理由要讲清产地、风味和保存方式。",
    avoid: "不要只看低价，优先看渠道、冷链和开果/果肉评价。",
    merchantSignal: "高客单潜在人群，适合讲风味、产地、冷链和礼盒价值。",
    liveHook: "如果你吃过金枕还想进阶，猫山王就是榴莲里的浓缩剧情。",
    color: "#f59f00",
    accent: "#7048e8",
  },
  "BLACK-X": {
    code: "BLACK-X",
    name: "黑刺高冷怪",
    pattern: "MHHHHLM",
    variety: "黑刺 / 小众进阶品种",
    form: "小众尝鲜装",
    cardLine: "你不是挑榴莲，你是在挑一种复杂的人生态度。",
    desc: "你能接受更重的气味和苦甜层次，也愿意为稀缺风味付出一点试错成本。适合被专业内容种草。",
    avoid: "小众品种要看清熟度、规格和售后边界，别只被名字带走。",
    merchantSignal: "老饕探索型用户，适合推小众品种、风味雷达和限量故事。",
    liveHook: "黑刺不是给所有人的，它适合已经不满足于甜的人。",
    color: "#212529",
    accent: "#fab005",
  },
  "D24-R": {
    code: "D24-R",
    name: "D24 复古人",
    pattern: "MMHMMLL",
    variety: "D24",
    form: "风味科普装",
    cardLine: "你不赶潮流，你只是相信稳定风味会自己说话。",
    desc: "你对风味有要求，但不喜欢太冒险。D24 适合做“有故事但不失控”的中阶推荐。",
    avoid: "先确认产地、冷冻/鲜果形式和预计口感，再决定是否入手。",
    merchantSignal: "稳健中阶用户，适合用科普内容和对比图转化。",
    liveHook: "D24 像老唱片，不一定最大声，但有自己的层次。",
    color: "#8ce99a",
    accent: "#2b8a3e",
  },
  "FROZEN-C": {
    code: "FROZEN-C",
    name: "冷冻理智派",
    pattern: "MLLMLLL",
    variety: "冷冻榴莲果肉",
    form: "即食果肉 / 小包装",
    cardLine: "你不是不爱榴莲，你只是不想被开果现场绑架。",
    desc: "你更需要确定、方便和低门槛。冷冻果肉能减少开果、成熟度和保存压力。",
    avoid: "看清配料、净含量、冷链和解冻建议，别被大包装视觉骗了。",
    merchantSignal: "便利优先用户，适合推即食、办公室、甜品场景。",
    liveHook: "怕麻烦的朋友别硬上整果，冷冻果肉是榴莲世界的快捷键。",
    color: "#74c0fc",
    accent: "#1864ab",
  },
  "GROUP-E": {
    code: "GROUP-E",
    name: "宿舍拼团王",
    pattern: "HMLLMHM",
    variety: "金枕拼团装",
    form: "多人拼团 / 社群团购",
    cardLine: "你买的不是榴莲，是一场能被全群围观的开果局。",
    desc: "你适合选择大众接受度高、单价可拆分、分享性强的品种。拼团能降低单人试错压力。",
    avoid: "拼团前先统一预算和臭味接受度，不然开果变开会。",
    merchantSignal: "裂变价值高，适合投放社群口令、多人测试和拼团优惠。",
    liveHook: "宿舍四个人拼一份，人均一杯奶茶钱，今晚就能开榴莲局。",
    color: "#ffd43b",
    accent: "#e64980",
  },
  "LOVE-G": {
    code: "LOVE-G",
    name: "爆浆恋爱脑",
    pattern: "HMLHMHL",
    variety: "金枕礼盒 / 榴莲甜品",
    form: "礼盒 / 甜品组合",
    cardLine: "你需要的不是水果，是一个能被认真拆开的仪式感。",
    desc: "你对甜感、氛围和送礼场景更敏感。适合推荐礼盒、甜品和聚会型产品。",
    avoid: "送礼别只看包装，也要看味道接受度和保存条件。",
    merchantSignal: "礼品场景用户，适合情绪价值、包装和节日节点转化。",
    liveHook: "这不是一份榴莲，这是今晚聚会的气氛按钮。",
    color: "#ff8787",
    accent: "#c2255c",
  },
  "VALUE-W": {
    code: "VALUE-W",
    name: "夹生打工人",
    pattern: "MMLLLMM",
    variety: "金枕 / 冷冻果肉",
    form: "性价比装 / 小份尝鲜",
    cardLine: "你不是抠，你是在认真保护自己的钱包和情绪。",
    desc: "你对价格和翻车都敏感，适合先从小份、拼团或保障更明确的商品开始。",
    avoid: "别被超低价冲昏头，低价也要看熟度、售后和真实评价。",
    merchantSignal: "价格敏感但可转化，适合优惠券、拼团和包熟承诺。",
    liveHook: "怕踩坑的朋友先别冲贵的，稳稳吃到才是第一原则。",
    color: "#adb5bd",
    accent: "#495057",
  },
  "CRACK-M": {
    code: "CRACK-M",
    name: "裂口发疯人",
    pattern: "MHMMLHH",
    hidden: true,
    variety: "黑暗品 / 裂口果",
    form: "当天开吃非标果",
    cardLine: "我裂开了，但我很甜。你看懂了这颗果的幽默。",
    desc: "你能接受不完美外观，只要缺点透明、价格合理、适合当天开吃。黑暗品数字名片就是为你这种人准备的。",
    avoid: "黑暗品必须明示瑕疵、风险和食用时限，不能把缺点包装成没有缺点。",
    merchantSignal: "黑暗品高意向用户，适合推裂口果、丑果和限时处理库存。",
    liveHook: "这颗长得比较抽象，但缺点明说、熟度够，适合今晚就吃。",
    color: "#40c057",
    accent: "#d9480f",
  },
  "ABSTRACT-H": {
    code: "ABSTRACT-H",
    name: "榴莲抽象派",
    pattern: "MMMMMMM",
    fallback: true,
    variety: "金枕小份尝鲜",
    form: "测试款 / 小份装",
    cardLine: "系统没完全看懂你，但它确信你值得一小口榴莲。",
    desc: "你的答案横跨多个流派，建议从低风险小份开始，用真实口感校准下一次推荐。",
    avoid: "先别冲高价和非标果，从小份、包熟、评价稳定的商品开始。",
    merchantSignal: "未定型新客，适合小样、优惠券和二次问答承接。",
    liveHook: "还不知道自己爱哪口，就先从小份甜糯款开始。",
    color: "#91a7ff",
    accent: "#364fc7",
  },
};

export const normalTypes = Object.values(typeLibrary).filter(
  (type) => !type.hidden && !type.fallback,
);

export const seedLeads = [
  { type: "GOLD-I", intent: 4, share: 5, dark: 1, variety: "泰国金枕", scene: "拼团" },
  { type: "GOLD-I", intent: 5, share: 4, dark: 2, variety: "泰国金枕", scene: "直播间" },
  { type: "GROUP-E", intent: 5, share: 5, dark: 2, variety: "金枕拼团装", scene: "拼团" },
  { type: "GROUP-E", intent: 4, share: 5, dark: 3, variety: "金枕拼团装", scene: "拼团" },
  { type: "VALUE-W", intent: 3, share: 3, dark: 2, variety: "冷冻果肉", scene: "独享" },
  { type: "VALUE-W", intent: 4, share: 2, dark: 3, variety: "金枕", scene: "社群" },
  { type: "FROZEN-C", intent: 3, share: 1, dark: 1, variety: "冷冻榴莲果肉", scene: "办公室" },
  { type: "FROZEN-C", intent: 4, share: 2, dark: 1, variety: "冷冻榴莲果肉", scene: "独享" },
  { type: "MUSANG-P", intent: 5, share: 2, dark: 1, variety: "猫山王", scene: "礼盒" },
  { type: "MUSANG-P", intent: 4, share: 3, dark: 1, variety: "猫山王", scene: "独享" },
  { type: "BLACK-X", intent: 4, share: 2, dark: 2, variety: "黑刺", scene: "尝鲜" },
  { type: "D24-R", intent: 3, share: 2, dark: 1, variety: "D24", scene: "科普" },
  { type: "LOVE-G", intent: 5, share: 4, dark: 1, variety: "榴莲礼盒", scene: "送礼/聚会" },
  { type: "CRACK-M", intent: 5, share: 5, dark: 5, variety: "裂口果", scene: "黑暗品" },
  { type: "CRACK-M", intent: 4, share: 5, dark: 5, variety: "丑果", scene: "黑暗品" },
];

export const darkDefects = [
  {
    id: "crack",
    label: "裂口",
    name: "裂口小王子",
    risk: "建议当天开吃，运输和保存时间不宜过长。",
    upside: "熟度更明显，价格更香，适合敢尝试的人。",
  },
  {
    id: "shape",
    label: "形状不规则",
    name: "歪头爆浆选手",
    risk: "外观不体面，不适合作为正式送礼。",
    upside: "不影响核心果肉判断，适合自吃和拼团。",
  },
  {
    id: "spot",
    label: "刺不均匀",
    name: "刺头甜心",
    risk: "需要主播/商家补充熟度和开果说明。",
    upside: "外表有争议，但可用透明说明降低顾虑。",
  },
];
